# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/software/lpGBT/lpgbt-fpga-kcu105/mgt/10g24/xlx_ku_mgt_ip_10g24.xci
# IP: The module: 'xlx_ku_mgt_ip_10g24' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/software/lpGBT/lpgbt-fpga-kcu105/mgt/10g24/synth/xlx_ku_mgt_ip_10g24_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlx_ku_mgt_ip_10g24'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/software/lpGBT/lpgbt-fpga-kcu105/mgt/10g24/synth/xlx_ku_mgt_ip_10g24.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlx_ku_mgt_ip_10g24'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/software/lpGBT/lpgbt-fpga-kcu105/mgt/10g24/xlx_ku_mgt_ip_10g24.xci
# IP: The module: 'xlx_ku_mgt_ip_10g24' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/software/lpGBT/lpgbt-fpga-kcu105/mgt/10g24/synth/xlx_ku_mgt_ip_10g24_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlx_ku_mgt_ip_10g24'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/software/lpGBT/lpgbt-fpga-kcu105/mgt/10g24/synth/xlx_ku_mgt_ip_10g24.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlx_ku_mgt_ip_10g24'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
