@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.3 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Jan 24 21:19:20 +0700 2020
REM SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim SCA_work_TB_behav -key {Behavioral:sim_1:Functional:SCA_work_TB} -tclbatch SCA_work_TB.tcl -view F:/Users/Alexey/Project/CERN/Xilinx/lpGBT_Project/lpgbt-fpga-kcu105_Ver_8/lpgbt-fpga-kcu105_Ver_8.srcs/sim_1/imports/Alexey_BTL/lpgbt-fpga-kcu105_Ver_1/EC_bits_TB_behav.wcfg -view F:/Users/Alexey/Project/CERN/Xilinx/lpGBT_Project/lpgbt-fpga-kcu105_Ver_8/lpgbt-fpga-kcu105_Ver_8.srcs/sim_1/imports/lpgbt-fpga-kcu105_Ver_3/SCA_work_TB_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
