# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Alexey_BTL/lpgbt-fpga-kcu105/constraints/kcu105_clks.xdc

# XDC: imports/Alexey_BTL/lpgbt-fpga-kcu105/constraints/kcu105_io.xdc

# TCL: imports/Alexey_BTL/ipBUS_Lib/constrs_1/clock_utils.tcl

# TCL: imports/Alexey_BTL/ipBUS_Lib/constrs_1/kcu105_basex.tcl

# IP: ip/gig_ethernet_pcs_pma_basex_156_25/gig_ethernet_pcs_pma_basex_156_25.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gig_ethernet_pcs_pma_basex_156_25 || ORIG_REF_NAME==gig_ethernet_pcs_pma_basex_156_25} -quiet] -quiet

# IP: ip/temac_gbe_v9_0/temac_gbe_v9_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==temac_gbe_v9_0 || ORIG_REF_NAME==temac_gbe_v9_0} -quiet] -quiet
