set_property SRC_FILE_INFO {cfile:/home/alkozyre/cernbox/Alexey_BTL/scripts/example/lpgbt-fpga-kcu105_Ver_9/lpgbt-fpga-kcu105_Ver_9.srcs/constrs_1/imports/Alexey_BTL/lpgbt-fpga-kcu105/constraints/kcu105_clks.xdc rfile:../../../lpgbt-fpga-kcu105_Ver_9.srcs/constrs_1/imports/Alexey_BTL/lpgbt-fpga-kcu105/constraints/kcu105_clks.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alkozyre/cernbox/Alexey_BTL/scripts/example/lpgbt-fpga-kcu105_Ver_9/lpgbt-fpga-kcu105_Ver_9.srcs/constrs_1/imports/Alexey_BTL/lpgbt-fpga-kcu105/constraints/kcu105_io.xdc rfile:../../../lpgbt-fpga-kcu105_Ver_9.srcs/constrs_1/imports/Alexey_BTL/lpgbt-fpga-kcu105/constraints/kcu105_io.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:/home/alkozyre/cernbox/Alexey_BTL/scripts/example/lpgbt-fpga-kcu105_Ver_9/lpgbt-fpga-kcu105_Ver_9.srcs/constrs_1/imports/Alexey_BTL/ipBUS_Lib/constrs_1/kcu105_basex.tcl rfile:../../../lpgbt-fpga-kcu105_Ver_9.srcs/constrs_1/imports/Alexey_BTL/ipBUS_Lib/constrs_1/kcu105_basex.tcl id:3 unmanaged:yes} [current_design]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G10 [get_ports USER_CLOCK_P]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F10 [get_ports USER_CLOCK_N]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V6 [get_ports SMA_MGT_REFCLK_P]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V5 [get_ports SMA_MGT_REFCLK_N]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path 2 -from [get_pins {lpgbtFpga_top_inst/uplink_inst/frame_pipelined_s_reg[*]/C}] -hold
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path 2 -from [get_pins -hierarchical -filter {NAME =~ lpgbtFpga_top_inst/uplink_inst/*descrambledData_reg[*]/C}] -hold
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -hold -to [get_pins -hierarchical -filter {NAME =~ lpgbtFpga_top_inst/downlink_inst/lpgbtfpga_scrambler_inst/scrambledData*/D}] 2
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN8 [get_ports CPU_RESET]
set_property src_info {type:XDC file:2 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D5 [get_ports SFP0_TX_N]
set_property src_info {type:XDC file:2 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D6 [get_ports SFP0_TX_P]
set_property src_info {type:XDC file:2 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D1 [get_ports SFP0_RX_N]
set_property src_info {type:XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D2 [get_ports SFP0_RX_P]
set_property src_info {type:XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL8 [get_ports SFP0_TX_DISABLE]
set_property src_info {type:XDC file:2 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H27 [get_ports USER_SMA_GPIO_P]
set_property src_info {type:XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G27 [get_ports USER_SMA_GPIO_N]
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A13    [get_ports ff_tx_prsnt_n ]; # FMC 1: LA03_p
set_property src_info {type:XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K10    [get_ports ff_rx_prsnt_n ]; # FMC 1: LA02_p
set_property src_info {type:XDC file:2 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L12    [get_ports ff_tx_int_n   ]; # FMC 1: LA04_p
set_property src_info {type:XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H11    [get_ports ff_rx_int_n   ]; # FMC 1: LA00_p
set_property src_info {type:XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K12    [get_ports ff_tx_reset_n ]; # FMC 1: LA04_n
set_property src_info {type:XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G9     [get_ports ff_rx_reset_n ]; # FMC 1: LA01_p
set_property src_info {type:XDC file:2 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A12    [get_ports ff_tx_select_n]; # FMC 1: LA03_n
set_property src_info {type:XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G11    [get_ports ff_rx_select_n]; # FMC 1: LA00_n
set_property src_info {type:XDC file:3 line:30 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN P6 [get_ports eth_clk_p]
set_property src_info {type:XDC file:3 line:31 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN P5 [get_ports eth_clk_n]
set_property src_info {type:XDC file:3 line:41 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN T2 [get_ports eth_rx_p]
set_property src_info {type:XDC file:3 line:42 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN T1 [get_ports eth_rx_n]
set_property src_info {type:XDC file:3 line:43 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN U4 [get_ports eth_tx_p]
set_property src_info {type:XDC file:3 line:44 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN U3 [get_ports eth_tx_n]
set_property src_info {type:XDC file:3 line:49 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN AP8 [get_ports {leds[0]}]
set_property src_info {type:XDC file:3 line:50 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN H23 [get_ports {leds[1]}]
set_property src_info {type:XDC file:3 line:51 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN P20 [get_ports {leds[2]}]
set_property src_info {type:XDC file:3 line:52 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN P21 [get_ports {leds[3]}]
set_property src_info {type:XDC file:3 line:57 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN AN16 [get_ports {dip_sw[0]}]
set_property src_info {type:XDC file:3 line:58 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN AN19 [get_ports {dip_sw[1]}]
set_property src_info {type:XDC file:3 line:59 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN AP18 [get_ports {dip_sw[2]}]
set_property src_info {type:XDC file:3 line:60 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN AN14 [get_ports {dip_sw[3]}]
set_property src_info {type:XDC file:3 line:64 export:INPUT save:NONE read:READ} [current_design]
set_property LOC GTHE3_CHANNEL_X0Y10 [get_cells -hier -filter {name=~infra/eth/*/*GTHE3_CHANNEL_PRIM_INST}]
set_property src_info {type:XDC file:3 line:76 export:INPUT save:NONE read:READ} [current_design]
set_multicycle_path 2 -hold  -from [get_pins payload/example/FER_RST_StrbAll_s_reg/C]
set_property src_info {type:XDC file:3 line:78 export:INPUT save:NONE read:READ} [current_design]
set_multicycle_path 2 -hold  -from [get_pins payload/example/ErrCntStrbOR_s_reg/C]
set_property src_info {type:XDC file:3 line:114 export:INPUT save:NONE read:READ} [current_design]
set_multicycle_path 2 -hold  -from [get_pins {payload/example/lpGBTsc_inst/sca_inst/sca_gen[0].rx_inst/sca_deserializer_inst/cnter_reg[*]/C}]
set_property src_info {type:XDC file:3 line:117 export:INPUT save:NONE read:READ} [current_design]
set_multicycle_path 2 -hold  -from [get_pins {payload/example/lpGBTsc_inst/sca_inst/sca_gen[0].rx_inst/sca_deserializer_inst/reg_no_destuffing_reg[*]/C}]
set_property src_info {type:XDC file:3 line:120 export:INPUT save:NONE read:READ} [current_design]
set_multicycle_path 2 -hold  -from [get_pins lpgbtFpga_top_inst/uplink_inst/rdy_1_s_reg/C]
set_property src_info {type:XDC file:3 line:123 export:INPUT save:NONE read:READ} [current_design]
set_multicycle_path 2 -hold  -from [get_pins {payload/example/lpGBTsc_inst/sca_inst/sca_gen[0].rx_inst/sca_deserializer_inst/ongoing_reg/C}]
set_property src_info {type:XDC file:3 line:126 export:INPUT save:NONE read:READ} [current_design]
set_multicycle_path 2 -hold  -to [get_pins payload/example/rd_to_gbtic_Trig_si_reg/D]
set_property src_info {type:XDC file:3 line:129 export:INPUT save:NONE read:READ} [current_design]
set_multicycle_path 2 -hold  -from [get_pins {payload/example/lpGBTsc_inst/ic_inst/tx_inst/reg_pos_reg[*]/C}]
set_property src_info {type:XDC file:3 line:140 export:INPUT save:NONE read:READ} [current_design]
set_multicycle_path 3 -hold -from [get_clocks -filter {name =~ *rxoutclk*}] -to [get_clocks ipbus_clk]
set_property src_info {type:XDC file:3 line:144 export:INPUT save:NONE read:READ} [current_design]
set_multicycle_path 2 -hold -end -from [get_clocks ipbus_clk] -to [get_clocks -filter {name =~ *rxoutclk*}]
